name: CI Build and Test

on:
  pull_request:
    branches: [ "main", "dev" ] # Roda apenas quando um PR é aberto para estas branches

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Disable shallow clone so SonarQube can scan PR differences properly
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install
      
    - name: Run lint
      run: npm run lint
      
    - name: Run Build
      run: npm run build
      
    - name: Run tests (with coverage)
      run: npm run test:cov

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}